module.exports = {
	navTitleCart: '购物车',
	navTitleAccount: '我的账户',
	navTitleMyInfo: '我的信息',
	navTitleSetting: '账户设置',
	navTitleChangeName: '修改显示名称',
	navTitleAboutUs: '关于WeBuy',
	navTitleAddressBook: '地址薄',
	navTitleSelectCountry: '选择国家/地区',
	navTitleCurrency: '货币',
	navTitleLanguage: '语言',
	navTitleAbout: '关于',
	navTitleTerms: '条款',
	navTitlePrivacyPolicy: '隐私政策',
	
	placeholderMail: '请输入邮箱',
	placeholderPwd: '请输入密码',
	placeholderUserName: '请输入显示名称',
	
	publicMale: '男士',
	publicFemale: '女士',
	publicSave: '保存',
	publicLogin: '登录',
	publicLogout: '登出',
	publicNextStep: '下一步',
	
	loadingDown: "上拉显示更多",
	loadingFresh: "正在加载...",
	loadingNomore: "没有更多数据了",
	
	accountUnlogin: '登录/注册',
	accountFuncWish: '心愿单',
	accountFuncHisgtory: '历史',
	accountAllOrder: '全部订单',
	accountOrderUnpaid: '未付款',
	accountOrderPreparing: '待发货',
	accountOrderShipped: '待收货',
	accountOrderReviews: '评价',
	accountOrderReturns: '退货列表',
	
	myInfoAvatar: '头像',
	myInfoName: '显示名称',
	myInfoBirthday: '生日',
	myInfoGender: '性别',
	
	settingMyInfo: '我的信息',
	settingAddress: '配送地址',
	settingLanguage: '语言',
	settingCurrency: '货币',
	settingCountry: '国家/地区',
	settingPhone: '手机号',
	settingEmail: '电子邮件',
	settingChangePwd: '更改密码',
	settingAboutUs: '关于WeBuy',
	settingRateUs: '给我们评价',
	settingAbout: '关于',
	settingTerms: '条款',
	settingPrivacyPolicy: '隐私政策',
	
	bindPhoneText: '绑定手机号',
	bindPhoneRemind: '绑定之后即可用此手机号登录'
}