module.exports = {
	navTitleCart: '购物车',
	navTitleAccount: '我的账户',
	navTitleMyInfo: '我的信息',
	navTitleSetting: '账户设置',
	navTitleChangeName: '修改显示名称',
	navTitleAboutUs: '关于WeBuy',
	navTitleAddressBook: '地址薄',
	navTitleSelectCountry: '选择国家/地区',
	navTitleCurrency: '货币',
	navTitleLanguage: '语言',
	navTitleAbout: '关于',
	navTitleTerms: '条款',
	navTitlePrivacyPolicy: '隐私政策',
	navTitleProvince: '选择您的州/省/地区',
	navTitleCity: '选择您的城市',
	navTitleHistory: '历史',
	navTitleWish: '心愿单',
	navTitleFindMore: '相似商品',
	navTitleBuyyerReading: '购买须知',
	navTitleSizeGuide: '尺寸指南',
	navTitleAppraise: '发表评价',
	navTitleAppraiseList: '评价',
	
	placeholderMail: '请输入邮箱',
	placeholderPwd: '请输入密码',
	placeholderUserName: '请输入显示名称',
	placeholderPhone: '请输入手机号码',
	placeholderVerCode: '请输入验证码',
	placeholderSelect: '请选择',
	placeholderOption: '可选项',
	
	publicMale: '男士',
	publicFemale: '女士',
	publicSave: '保存',
	publicLogin: '登录',
	publicLogout: '登出',
	publicConfirm: '确定',
	publicCancel: '取消',
	publicNextStep: '下一步',
	publicEdit: '编辑',
	publicFinish: '完成',
	publicDefault: '默认',
	
	loadingDown: "上拉显示更多",
	loadingFresh: "正在加载...",
	loadingNomore: "没有更多数据了",
	
	accountUnlogin: '登录/注册',
	accountFuncWish: '心愿单',
	accountFuncHistory: '历史',
	accountAllOrder: '全部订单',
	accountOrderUnpaid: '未付款',
	accountOrderPreparing: '待发货',
	accountOrderShipped: '待收货',
	accountOrderReviews: '评价',
	accountOrderReturns: '退货列表',
	
	myInfoAvatar: '头像',
	myInfoName: '显示名称',
	myInfoBirthday: '生日',
	myInfoGender: '性别',
	
	settingMyInfo: '我的信息',
	settingAddress: '配送地址',
	settingLanguage: '语言',
	settingCurrency: '货币',
	settingCountry: '国家/地区',
	settingPhone: '手机号',
	settingEmail: '电子邮件',
	settingChangePwd: '更改密码',
	settingAboutUs: '关于WeBuy',
	settingRateUs: '给我们评价',
	settingAbout: '关于',
	settingTerms: '条款',
	settingPrivacyPolicy: '隐私政策',
	
	bindPhoneText: '绑定手机号',
	bindPhoneRemind: '绑定之后即可用此手机号登录',
	bindSmsText: '请输入验证码',
	bindSmsRemind: '验证码已发送至：',
	bindVerTime: ' 秒\n重新发送',
	bindVerResend: '发送验证码',
	
	changePwdText: '更新您的密码',
	changePwdOldPwd: '原始密码',
	changePwdNewPwd: '新密码',
	changePwdConfirmPwd: '确认密码',
	changePwdNewRemind: '您的密码必须是6-20个字符',
	changePwdConfirmRemind: '密码不匹配！',
	
	emailText: '输入新电子邮箱',
	emailRemind: '更改后您可以使用新的电子邮箱登录',
	
	addressNew: '新增地址',
	addressEditTitle: '编辑收货地址',
	addressAddTitle: '添加收货地址',
	addressFirstName: '名：',
	addressLastName: '姓：',
	addressCountry: '国家/地区：',
	addressState: '州/省/地区：',
	addressCity: '城市：',
	addressLine1: '地址1：',
	addressLine2: '地址2：',
	addressPostalCode: '邮编/邮政区号：',
	addressPhone: '手机号码：',
	addressAlternativePhone: '备用电话电码：',
	addressNote: '货运说明：',
	addressSetDefault: '设置为默认地址',
	addressPlaceAddress: '街道、地区、楼栋号、单元室等',
	
	searchPlace: '想买点儿撒',
	
	historyFindMore: '找相似商品'
}